spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
  liquibase:
    change-log: classpath:/database/changelog-master.yaml

server:
  port: 8080