
create table types
(
    id   UUID primary key,
    type varchar(255)
);
create table type_of_constructions
(
    id                UUID primary key,
    type_construction varchar(255)
);
create table buildings
(
    id                      UUID primary key,
    completion_time         varchar(255),
    house_type_id           UUID not null,
    type_of_construction_id UUID not null,
    constraint house_type_buildings_fk foreign key (house_type_id) references types,
    constraint type_of_construction_id foreign key references type_of_constructions (id)



        create table hall
        (
        id        int8 generated by default as identity,
        name      varchar(255) not null,
        cinema_id int8 not null,
        primary key (id)
        );

        alter table if exists hall
        add constraint hall_cinema_fk foreign key (cinema_id) references cinema;
);